export const BANGLADESH_TOURIST_LOCATIONS: string[] = [
  "Cox's Bazar, Bangladesh",
  "Saint Martin Island, Bangladesh",
  "Kuakata, Bangladesh",
  "Sajek Valley, Bangladesh",
  "Bandarban, Bangladesh",
  "Rangamati, Bangladesh",
  "Sreemangal, Bangladesh",
  "Sylhet, Bangladesh",
  "Sundarbans, Bangladesh",
  "Bisanakandi, Bangladesh",
  "Ratargul Swamp Forest, Bangladesh",
  "Tanguar Haor, Bangladesh",
  "Jaflong, Bangladesh",
  "Lalakhal, Bangladesh",
  "Nafakhum Waterfall, Bangladesh",
  "Nilgiri, Bandarban, Bangladesh",
  "Niladri Lake, Sunamganj, Bangladesh",
  "Paharpur, Bangladesh",
  "Mahasthangarh, Bangladesh",
  "Sonargaon, Bangladesh",
  "Panam City, Bangladesh",
  "Srimangal Tea Gardens, Bangladesh",
  "Dhaka, Bangladesh",
  "Chattogram, Bangladesh",
  "Khulna, Bangladesh",
  "Rajshahi, Bangladesh",
  "Barishal, Bangladesh"
];

export const GLOBAL_TOURIST_LOCATIONS: string[] = [
  "Maldives",
  "Bali, Indonesia",
  "Phuket, Thailand",
  "Bangkok, Thailand",
  "Chiang Mai, Thailand",
  "Singapore",
  "Kuala Lumpur, Malaysia",
  "Langkawi, Malaysia",
  "Dubai, United Arab Emirates",
  "Mecca, Saudi Arabia",
  "Istanbul, Turkey",
  "Paris, France",
  "Rome, Italy",
  "Santorini, Greece",
  "Barcelona, Spain",
  "Swiss Alps, Switzerland",
  "London, United Kingdom",
  "New York, United States",
  "Los Angeles, United States",
  "Toronto, Canada",
  "Tokyo, Japan",
  "Kyoto, Japan",
  "Seoul, South Korea",
  "Sydney, Australia",
  "Auckland, New Zealand",
  "Cairo, Egypt",
  "Makkah, Saudi Arabia",
  "Madinah, Saudi Arabia"
];
